#!/usr/bin/env python3
"""Generate tests/functions.zig (raylib's RLAPI functions + raymath's RMAPI names) from the pinned headers.
Run from the repo root: python3 tools/gen_functions.py [--raylib /tmp/rlzsrc/raylib] [--out tests/functions.zig]"""

import argparse
import os
import re
import sys

# The raylib these counts were taken from; bump both together when the pin moves.
PINNED_COMMIT = "f0e501203d18f9c254fbabca353d08b8f4c698ac"
PINNED_VERSION = "raylib 6.1-dev"

# Per-module RLAPI counts as declared by raylib.h's own section headers.
EXPECTED_MODULES = {
    "core": 211,
    "rgestures": 8,
    "rcamera": 2,
    "shapes": 75,
    "textures": 125,
    "text": 59,
    "models": 73,
    "audio": 66,
}
EXPECTED_RAYLIB = sum(EXPECTED_MODULES.values())  # 619
EXPECTED_RAYMATH = 146

# raylib.h's core module is split over three raylibz files, by raylib.h's own section comments:
# core.zig up to "File system management functions", files.zig from there (files, file callbacks,
# compression, automation events), and input.zig for "Input Handling Functions (Module: core)" and
# the rgestures and rcamera sections.
FILES_SECTION = "File system management functions"
INPUT_HEADER = "Input Handling Functions"
FILE_OVERRIDES = {"rgestures": "input", "rcamera": "input"}

MODULE_HEADER_RE = re.compile(r"\(\s*Module:\s*([A-Za-z_][A-Za-z0-9_]*)\s*\)")
IDENT_RE = re.compile(r"([A-Za-z_][A-Za-z0-9_]*)\s*$")

HEADER = f"""//! Generated by tools/gen_functions.py from raylib's raylib.h and raymath.h at
//! commit {PINNED_COMMIT} ({PINNED_VERSION}). Do not edit
//! by hand; re-run the generator. Names only: raylib's declarations are
//! Copyright (c) 2013-2026 Ramon Santamaria (@raysan5) and its contributors,
//! under the zlib license (see NOTICE).

/// One RLAPI function of raylib.h: its C name, the module raylib.h files it
/// under, and the raylibz module file that must hold its wrapper.
pub const Function = struct {{
    /// The C name, e.g. `InitWindow`.
    name: []const u8,
    /// The module of raylib.h's section header, e.g. `core`. `rgestures` and
    /// `rcamera` are their own sections of raylib.h.
    module: []const u8,
    /// The raylibz module file that must hold this function's wrapper: `core`
    /// also holds rgestures and rcamera.
    file: []const u8,
}};
"""


def die(message):
    sys.exit(f"gen_functions.py: error: {message}")


def declared_name(declarator, path, lineno, macro):
    """The function name of a `MACRO <type> <name>(params...)` declaration line."""
    head = declarator.split("(", 1)[0]  # drop the parameter list
    match = IDENT_RE.search(head)
    if not match:
        die(f"{path}:{lineno}: cannot find a function name in `{macro}{declarator}`")
    return match.group(1)


def parse_raylib(path):
    """[(name, module, file)] for every RLAPI declaration of raylib.h, in declaration order."""
    functions = []
    module = None
    file = None
    with open(path, encoding="utf-8") as handle:
        for lineno, line in enumerate(handle, 1):
            if line.lstrip().startswith("//"):
                match = MODULE_HEADER_RE.search(line)
                if match:
                    module = match.group(1)
                    file = "input" if INPUT_HEADER in line else FILE_OVERRIDES.get(module, module)
                    continue
                if module == "core" and FILES_SECTION in line:
                    file = "files"
            if not line.startswith("RLAPI"):
                continue
            if module is None:
                die(f"{path}:{lineno}: RLAPI declaration before any `(Module: ...)` section header")
            functions.append((declared_name(line[len("RLAPI"):], path, lineno, "RLAPI"), module, file))
    return functions


def parse_raymath(path):
    """[name] for every RMAPI function of raymath.h, in declaration order."""
    names = []
    with open(path, encoding="utf-8") as handle:
        for lineno, line in enumerate(handle, 1):
            if not line.startswith("RMAPI"):
                continue  # skips the `#define RMAPI ...` lines, which are indented
            names.append(declared_name(line[len("RMAPI"):], path, lineno, "RMAPI"))
    return names


def check_raylib(functions):
    counts = {}
    for _, module, _ in functions:
        counts[module] = counts.get(module, 0) + 1
    problems = []
    for module, expected in EXPECTED_MODULES.items():
        found = counts.get(module, 0)
        if found != expected:
            problems.append(f"{module}: expected {expected}, found {found}")
    for module in sorted(set(counts) - set(EXPECTED_MODULES)):
        problems.append(f"unknown module `{module}` with {counts[module]} functions")
    if len(functions) != EXPECTED_RAYLIB:
        problems.append(f"total: expected {EXPECTED_RAYLIB}, found {len(functions)}")
    names = [name for name, _, _ in functions]
    duplicates = sorted({name for name in names if names.count(name) > 1})
    if duplicates:
        problems.append(f"duplicate declarations: {', '.join(duplicates)}")
    if problems:
        die(
            "raylib.h does not match the pinned API - the pin moved or the header changed; "
            "update EXPECTED_MODULES in this script only after checking the new header:\n  "
            + "\n  ".join(problems)
        )
    return counts


def check_raymath(names):
    if len(names) != EXPECTED_RAYMATH:
        die(
            f"raymath.h has {len(names)} RMAPI functions, expected {EXPECTED_RAYMATH} - "
            "the pin moved or the header changed; update EXPECTED_RAYMATH in this script."
        )
    duplicates = sorted({name for name in names if names.count(name) > 1})
    if duplicates:
        die(f"raymath.h declares duplicates: {', '.join(duplicates)}")


def render(functions, raymath_names):
    out = [HEADER]
    out.append("\n/// Every RLAPI function of the pinned raylib.h, in declaration order.\n")
    out.append(f"pub const raylib: [{len(functions)}]Function = .{{\n")
    for name, module, file in functions:
        out.append(f'    .{{ .name = "{name}", .module = "{module}", .file = "{file}" }},\n')
    out.append("};\n")
    out.append("\n/// Every RMAPI function of the pinned raymath.h, in declaration order.\n")
    out.append(f"pub const raymath: [{len(raymath_names)}][]const u8 = .{{\n")
    for name in raymath_names:
        out.append(f'    "{name}",\n')
    out.append("};\n")
    return "".join(out)


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--raylib", default="/tmp/rlzsrc/raylib", help="raylib checkout holding src/raylib.h and src/raymath.h")
    parser.add_argument("--out", default="tests/functions.zig", help="generated Zig file")
    args = parser.parse_args()

    raylib_h = os.path.join(args.raylib, "src", "raylib.h")
    raymath_h = os.path.join(args.raylib, "src", "raymath.h")
    for path in (raylib_h, raymath_h):
        if not os.path.isfile(path):
            die(f"missing header: {path}")

    functions = parse_raylib(raylib_h)
    counts = check_raylib(functions)
    raymath_names = parse_raymath(raymath_h)
    check_raymath(raymath_names)

    directory = os.path.dirname(args.out)
    if directory:
        os.makedirs(directory, exist_ok=True)
    with open(args.out, "w", encoding="utf-8") as handle:
        handle.write(render(functions, raymath_names))

    print(f"wrote {args.out} from {args.raylib}")
    print(f"raylib.h: {len(functions)} RLAPI functions")
    for module in counts:
        print(f"  {module:<9} {counts[module]:>3}")
    print(f"raymath.h: {len(raymath_names)} RMAPI functions")


if __name__ == "__main__":
    main()
